### ISSUE TITLE
Local Windows git push fails on pre-existing, unrelated typecheck/test failures unconnected to the change being pushed

### ISSUE THREAD

**Issue by Yogitmeister** [Nimbalyst/nimbalyst#878]
On Windows, \`.githooks/pre-push\` runs \`npm run typecheck -ws --if-present\`
before workspace build artifacts (\`@nimbalyst/runtime\`, \`@nimbalyst/extension-sdk\`,
the memory-engine) exist, producing cascading "cannot find module" typecheck
failures unrelated to any actual change.

Separately, ~18 Vitest suites fail deterministically on Windows only (CI has no
Windows runner — \`.github/workflows/ci.yml\` is Ubuntu-only — so these were
never covered there either) and block every local Windows push regardless of
what's being pushed.

## Fix (PR incoming)
- A \`typecheck:prepush\` npm script builds the required workspace prerequisites
  before typechecking.
- A per-suite (not blanket) exclusion of the 18 explicitly-named,
  live-verified-failing suites on local Windows only — never CI, never other
  platforms. Any new suite, including ones added after the exclusion list,
  still runs and blocks a local Windows push on failure. Implemented via
  \`vitest.config.ts\`'s per-project \`exclude\` arrays (this repo's
  \`test.projects\` config means a vitest CLI \`--exclude\` flag does not reach
  file discovery for either project — confirmed live), gated by an env var
  only the local pre-push script sets.
- A worker-concurrency cap (\`--maxWorkers 4\`) on local Windows runs only. The
  full suite at default (CPU-count) concurrency deterministically failed a
  handful of SQLite/PGLite-native-binding-backed suites with \`errno 44\`
  unhandled rejections — 100% passing in isolation, not fixed by retrying.
  Capping concurrency eliminates the contention outright.

**Comment by karlwirth** [comment]
Closing this, with one honest caveat about scope.

The pre-push gate no longer blocks on unrelated pre-existing failures: the root typecheck builds its prerequisites first, and the hook skips the full local Windows Vitest run while keeping CI and non-Windows coverage intact.

The caveat is that the Windows suite is skipped locally rather than made portable. So the symptom you hit is gone, but the underlying portability work was not done. If you would rather see that tracked, please open a separate issue and we will keep it.

The change shipped in 0.70.0.
